### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by ChrisLTD**
I took the liberty of designing a new icon based on the newer Safari icon, and the Vim “V”. 

Retina sizes are included.

screen shot 2015-08-12 at 2 54 20 pm

### CODE REVIEW

**Comment by simeg** [comment]
Hey @jasonlong. This looks great!

**Comment by ChrisLTD** [comment]
@simeg,
Have you officially taken over the project from Guy?

**Comment by simeg** [comment]
@ChrisLTD I'm helping Guy to maintain the project, he's still the owner though.

**Comment by simeg** [comment]
@ChrisLTD Would it be possible to get these in 32x32 and 48x48 as well?

**Pull request merged**
